name = "DatasetTools"
uuid = "a88e84b3-4851-473a-862c-cb491828dda2"
authors = ["Panos Margaris"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
